### ISSUE TITLE
Models trained on DexYCB can't be loaded

### ISSUE THREAD

**Issue by Arka-h** [amathislab/HOISDF#10]
When following the instructions and pointing the test.py script to ckpts as downloaded from https://zenodo.org/records/11668766, `dexycb/snapshot_dexycb.pth.tar`, `dexycb_full/snapshot_dexycb_full.pth.tar`, and `ho3d_render/snapshot_ho3d_render.pth.tar`
result in 
```
RuntimeError: Error(s) in loading state_dict for DataParallel:
Missing key(s) in state_dict:
...
Unexpected key(s) in state_dict: 
...
size mismatch for module.decoder_net.resnet_decoder.*
...
```

Upon inspection, we can see that the file sizes of these are identical (~625MB ± 5MB) 
However, 

`ho3d/snapshot_ho3d.pth.tar` has size of 1.4GB indicating different model structures.
Kindly update the 3 ckpt weights, to align with the given architecture, or provide code to load the ckpts.

**Comment by HaozheQi** [comment]
Hello, thanks for your interest.
The problem happens because you didn't change the `setting` option in `config.py` as illustrated [here](https://github.com/amathislab/HOISDF?tab=readme-ov-file#dexycb). 
The size difference of the trained ho3d checkpoint comes from the decoder size setting from [here](https://github.com/amathislab/HOISDF/blob/main/main/config.py#L96), we use a bigger image decoder for that setting similar to [keypoint transformer](https://github.com/shreyashampali/kypt_transformer?tab=readme-ov-file#ho-3d-v2-table-2-in-paper)

**Comment by Arka-h** [comment]
Thanks for the prompt response. 
Apologies for the oversight.
