### ISSUE TITLE
How to Use the Model for Inference on Custom Data?

### ISSUE THREAD

**Issue by Bokai-Ji** [amathislab/HOISDF#5]
Hello,

First of all, thank you for the fantastic work on this project! I have been able to get everything up and running smoothly, but I have a question regarding the usage of the model for inference on custom data.

Could you please provide guidance on how to properly use the model to perform inference on my own dataset? Specifically, I am looking for details on:

- **Data Preparation**: What format should the custom data be in? Are there any specific preprocessing steps that need to be followed?
- **Inference Procedure**: What are the exact steps to run inference on the custom data? Is there an existing script or function that can be used for this purpose?
- **Output**: What format will the output be in, and how can I interpret or visualize the results?

Any code snippets or examples would be greatly appreciated.

Thank you in advance for your assistance!

**Comment by HaozheQi** [comment]
Hi Bokai,

Thanks for your interest in our work. Here are the possible solutions to run on customized data.

- **Data Preparation:** If you only want to do inference on your data, you only to prepare cropped images with the interesting hand and object. Otherwise, if you want to fine-tune the model, you need to preprocess the GT annotations to generate SDF data following [AlignSDF](https://github.com/zerchen/AlignSDF?tab=readme-ov-file#dataset-preprocessing).
- **Inference Procedure:**  You could check our implementation of the data loading (e.g., [ho3d.py](https://github.com/amathislab/HOISDF/blob/main/data/ho3d.py)) to process the data and send the obtained data to the model to get the results.
- **Output:** For the hand prediction, you will obtain both the hand mesh and hand pose joints in MANO format [here](https://github.com/amathislab/HOISDF/blob/main/main/model.py#L616-L620). For the object prediction, you will obtain the object rotation and translation [here](https://github.com/amathislab/HOISDF/blob/main/main/model.py#L623-L624).

**Comment by Bokai-Ji** [comment]
Many thanks!
